name: Test Node with workflow
on: push
jobs:
  first-job:
    name: Build with Node
    runs-on: ubuntu-latest
    container: node:12.18.4
    steps:
      - name: Check Node.js version
        run: node --version
      - name: Check NPM version
        run: npm --version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Execute Node application
        run: node index.js